# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{kaltura-ruby}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["papyromancer"]
  s.date = %q{2010-07-01}
  s.email = %q{papyromancer@papyromancer.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "VERSION.yml",
     "kaltura-ruby.gemspec",
     "lib/kaltura.rb",
     "lib/kaltura/kaltura_client.rb",
     "lib/kaltura/kaltura_client/access_control_order_by.rb",
     "lib/kaltura/kaltura_client/audio_codec.rb",
     "lib/kaltura/kaltura_client/base_entry_order_by.rb",
     "lib/kaltura/kaltura_client/base_job_order_by.rb",
     "lib/kaltura/kaltura_client/base_syndication_feed_order_by.rb",
     "lib/kaltura/kaltura_client/batch_job_order_by.rb",
     "lib/kaltura/kaltura_client/batch_job_status.rb",
     "lib/kaltura/kaltura_client/batch_job_type.rb",
     "lib/kaltura/kaltura_client/bit_rate_mode.rb",
     "lib/kaltura/kaltura_client/category_order_by.rb",
     "lib/kaltura/kaltura_client/commercial_use_type.rb",
     "lib/kaltura/kaltura_client/container_format.rb",
     "lib/kaltura/kaltura_client/control_panel_command_order_by.rb",
     "lib/kaltura/kaltura_client/control_panel_command_status.rb",
     "lib/kaltura/kaltura_client/control_panel_command_target_type.rb",
     "lib/kaltura/kaltura_client/control_panel_command_type.rb",
     "lib/kaltura/kaltura_client/conversion_profile_order_by.rb",
     "lib/kaltura/kaltura_client/country_restriction_type.rb",
     "lib/kaltura/kaltura_client/data_entry_order_by.rb",
     "lib/kaltura/kaltura_client/directory_restriction_type.rb",
     "lib/kaltura/kaltura_client/document_entry_order_by.rb",
     "lib/kaltura/kaltura_client/document_type.rb",
     "lib/kaltura/kaltura_client/duration_type.rb",
     "lib/kaltura/kaltura_client/editor_type.rb",
     "lib/kaltura/kaltura_client/email_ingestion_profile_status.rb",
     "lib/kaltura/kaltura_client/entry_moderation_status.rb",
     "lib/kaltura/kaltura_client/entry_status.rb",
     "lib/kaltura/kaltura_client/entry_type.rb",
     "lib/kaltura/kaltura_client/file_sync_object_type.rb",
     "lib/kaltura/kaltura_client/file_sync_order_by.rb",
     "lib/kaltura/kaltura_client/file_sync_status.rb",
     "lib/kaltura/kaltura_client/file_sync_type.rb",
     "lib/kaltura/kaltura_client/flavor_asset_status.rb",
     "lib/kaltura/kaltura_client/gender.rb",
     "lib/kaltura/kaltura_client/google_syndication_feed_adult_values.rb",
     "lib/kaltura/kaltura_client/google_syndication_feed_order_by.rb",
     "lib/kaltura/kaltura_client/i_tunes_syndication_feed_adult_values.rb",
     "lib/kaltura/kaltura_client/i_tunes_syndication_feed_categories.rb",
     "lib/kaltura/kaltura_client/i_tunes_syndication_feed_order_by.rb",
     "lib/kaltura/kaltura_client/license_type.rb",
     "lib/kaltura/kaltura_client/live_stream_admin_entry_order_by.rb",
     "lib/kaltura/kaltura_client/mail_job_order_by.rb",
     "lib/kaltura/kaltura_client/media_entry_order_by.rb",
     "lib/kaltura/kaltura_client/media_type.rb",
     "lib/kaltura/kaltura_client/mix_entry_order_by.rb",
     "lib/kaltura/kaltura_client/moderation_flag_status.rb",
     "lib/kaltura/kaltura_client/moderation_flag_type.rb",
     "lib/kaltura/kaltura_client/moderation_object_type.rb",
     "lib/kaltura/kaltura_client/notification_order_by.rb",
     "lib/kaltura/kaltura_client/notification_type.rb",
     "lib/kaltura/kaltura_client/nullable_boolean.rb",
     "lib/kaltura/kaltura_client/partner_order_by.rb",
     "lib/kaltura/kaltura_client/partner_status.rb",
     "lib/kaltura/kaltura_client/partner_type.rb",
     "lib/kaltura/kaltura_client/playable_entry_order_by.rb",
     "lib/kaltura/kaltura_client/playlist_order_by.rb",
     "lib/kaltura/kaltura_client/playlist_type.rb",
     "lib/kaltura/kaltura_client/report_type.rb",
     "lib/kaltura/kaltura_client/search_provider_type.rb",
     "lib/kaltura/kaltura_client/session_type.rb",
     "lib/kaltura/kaltura_client/site_restriction_type.rb",
     "lib/kaltura/kaltura_client/source_type.rb",
     "lib/kaltura/kaltura_client/stats_event_type.rb",
     "lib/kaltura/kaltura_client/stats_kmc_event_type.rb",
     "lib/kaltura/kaltura_client/syndication_feed_status.rb",
     "lib/kaltura/kaltura_client/syndication_feed_type.rb",
     "lib/kaltura/kaltura_client/system_user_order_by.rb",
     "lib/kaltura/kaltura_client/system_user_status.rb",
     "lib/kaltura/kaltura_client/tube_mogul_syndication_feed_categories.rb",
     "lib/kaltura/kaltura_client/tube_mogul_syndication_feed_order_by.rb",
     "lib/kaltura/kaltura_client/ui_conf_creation_mode.rb",
     "lib/kaltura/kaltura_client/ui_conf_obj_type.rb",
     "lib/kaltura/kaltura_client/ui_conf_order_by.rb",
     "lib/kaltura/kaltura_client/upload_error_code.rb",
     "lib/kaltura/kaltura_client/user_order_by.rb",
     "lib/kaltura/kaltura_client/user_status.rb",
     "lib/kaltura/kaltura_client/video_codec.rb",
     "lib/kaltura/kaltura_client/widget_order_by.rb",
     "lib/kaltura/kaltura_client/widget_security_type.rb",
     "lib/kaltura/kaltura_client/yahoo_syndication_feed_adult_values.rb",
     "lib/kaltura/kaltura_client/yahoo_syndication_feed_categories.rb",
     "lib/kaltura/kaltura_client/yahoo_syndication_feed_order_by.rb",
     "lib/kaltura/kaltura_client_base.rb",
     "test/kaltura-ruby_test.rb",
     "test/test.rb",
     "test/test_2.rb",
     "test/test_error.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/papyromancer/kaltura-ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby gem for accessing the Kaltura API}
  s.test_files = [
    "test/kaltura-ruby_test.rb",
     "test/test.rb",
     "test/test_2.rb",
     "test/test_error.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<activeresource>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<rest-client>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<activeresource>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<rest-client>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<activeresource>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<rest-client>, [">= 0"])
  end
end
