require 'kaltura/constants/access_control_order_by'
require 'kaltura/constants/audio_codec'
require 'kaltura/constants/base_entry_order_by'
require 'kaltura/constants/base_job_order_by'
require 'kaltura/constants/base_syndication_feed_order_by'
require 'kaltura/constants/batch_job_order_by'
require 'kaltura/constants/batch_job_status'
require 'kaltura/constants/batch_job_type'
require 'kaltura/constants/bit_rate_mode'
require 'kaltura/constants/category_order_by'
require 'kaltura/constants/commercial_use_type'
require 'kaltura/constants/container_format'
require 'kaltura/constants/control_panel_command_order_by'
require 'kaltura/constants/control_panel_command_status'
require 'kaltura/constants/control_panel_command_target_type'
require 'kaltura/constants/control_panel_command_type'
require 'kaltura/constants/conversion_profile_order_by'
require 'kaltura/constants/country_restriction_type'
require 'kaltura/constants/data_entry_order_by'
require 'kaltura/constants/directory_restriction_type'
require 'kaltura/constants/document_entry_order_by'
require 'kaltura/constants/document_type'
require 'kaltura/constants/duration_type'
require 'kaltura/constants/editor_type'
require 'kaltura/constants/email_ingestion_profile_status'
require 'kaltura/constants/entry_moderation_status'
require 'kaltura/constants/entry_status'
require 'kaltura/constants/entry_type'
require 'kaltura/constants/file_sync_object_type'
require 'kaltura/constants/file_sync_order_by'
require 'kaltura/constants/file_sync_status'
require 'kaltura/constants/file_sync_type'
require 'kaltura/constants/flavor_asset_status'
require 'kaltura/constants/gender'
require 'kaltura/constants/google_syndication_feed_adult_values'
require 'kaltura/constants/google_syndication_feed_order_by'
require 'kaltura/constants/i_tunes_syndication_feed_adult_values'
require 'kaltura/constants/i_tunes_syndication_feed_categories'
require 'kaltura/constants/i_tunes_syndication_feed_order_by'
require 'kaltura/constants/license_type'
require 'kaltura/constants/live_stream_admin_entry_order_by'
require 'kaltura/constants/mail_job_order_by'
require 'kaltura/constants/media_entry_order_by'
require 'kaltura/constants/media_type'
require 'kaltura/constants/mix_entry_order_by'
require 'kaltura/constants/moderation_flag_status'
require 'kaltura/constants/moderation_flag_type'
require 'kaltura/constants/moderation_object_type'
require 'kaltura/constants/notification_order_by'
require 'kaltura/constants/notification_type'
require 'kaltura/constants/nullable_boolean'
require 'kaltura/constants/partner_order_by'
require 'kaltura/constants/partner_status'
require 'kaltura/constants/partner_type'
require 'kaltura/constants/playable_entry_order_by'
require 'kaltura/constants/playlist_order_by'
require 'kaltura/constants/playlist_type'
require 'kaltura/constants/report_type'
require 'kaltura/constants/search_provider_type'
require 'kaltura/constants/session_type'
require 'kaltura/constants/site_restriction_type'
require 'kaltura/constants/source_type'
require 'kaltura/constants/stats_event_type'
require 'kaltura/constants/stats_kmc_event_type'
require 'kaltura/constants/syndication_feed_status'
require 'kaltura/constants/syndication_feed_type'
require 'kaltura/constants/system_user_order_by'
require 'kaltura/constants/system_user_status'
require 'kaltura/constants/tube_mogul_syndication_feed_categories'
require 'kaltura/constants/tube_mogul_syndication_feed_order_by'
require 'kaltura/constants/ui_conf_obj_type'
require 'kaltura/constants/ui_conf_creation_mode'
require 'kaltura/constants/ui_conf_order_by'
require 'kaltura/constants/upload_error_code'
require 'kaltura/constants/user_order_by'
require 'kaltura/constants/user_status'
require 'kaltura/constants/video_codec'
require 'kaltura/constants/widget_order_by'
require 'kaltura/constants/widget_security_type'
require 'kaltura/constants/yahoo_syndication_feed_adult_values'
require 'kaltura/constants/yahoo_syndication_feed_categories'
require 'kaltura/constants/yahoo_syndication_feed_order_by'

module Kaltura
  module Constants
  
	  class KalturaFlavorParamsOrderBy
	  end

	  class KalturaFlavorParamsOutputOrderBy
	  end
	
	  class KalturaMediaInfoOrderBy
	  end
	    
  end
end