module Kaltura
  
	class KalturaReportType
		TOP_CONTENT = 1
		CONTENT_DROPOFF = 2
		CONTENT_INTERACTIONS = 3
		MAP_OVERLAY = 4
		TOP_CONTRIBUTORS = 5
		TOP_SYNDICATION = 6
		CONTENT_CONTRIBUTIONS = 7
		ADMIN_CONSOLE = 10
	end

end