module Kaltura
  
	class KalturaBatchJobType
		CONVERT = 0
		IMPORT = 1
		DELETE = 2
		FLATTEN = 3
		BULKUPLOAD = 4
		DVDCREATOR = 5
		DOWNLOAD = 6
		OOCONVERT = 7
		CONVERT_PROFILE = 10
		POSTCONVERT = 11
		PULL = 12
		REMOTE_CONVERT = 13
		EXTRACT_MEDIA = 14
		MAIL = 15
		NOTIFICATION = 16
		CLEANUP = 17
		SCHEDULER_HELPER = 18
		BULKDOWNLOAD = 19
		DB_CLEANUP = 20
		PROVISION_PROVIDE = 21
		CONVERT_COLLECTION = 22
		STORAGE_EXPORT = 23
		PROVISION_DELETE = 24
		STORAGE_DELETE = 25
		EMAIL_INGESTION = 26
		PROJECT = 1000
	end
	
end