module Kaltura
  module Constants
    module ITunesSyndicationFeed
      class Categories
    		ARTS = "Arts"
    		ARTS_DESIGN = "Arts/Design"
    		ARTS_FASHION_BEAUTY = "Arts/Fashion &amp; Beauty"
    		ARTS_FOOD = "Arts/Food"
    		ARTS_LITERATURE = "Arts/Literature"
    		ARTS_PERFORMING_ARTS = "Arts/Performing Arts"
    		ARTS_VISUAL_ARTS = "Arts/Visual Arts"
    		BUSINESS = "Business"
    		BUSINESS_BUSINESS_NEWS = "Business/Business News"
    		BUSINESS_CAREERS = "Business/Careers"
    		BUSINESS_INVESTING = "Business/Investing"
    		BUSINESS_MANAGEMENT_MARKETING = "Business/Management &amp; Marketing"
    		BUSINESS_SHOPPING = "Business/Shopping"
    		COMEDY = "Comedy"
    		EDUCATION = "Education"
    		EDUCATION_TECHNOLOGY = "Education/Education Technology"
    		EDUCATION_HIGHER_EDUCATION = "Education/Higher Education"
    		EDUCATION_K_12 = "Education/K-12"
    		EDUCATION_LANGUAGE_COURSES = "Education/Language Courses"
    		EDUCATION_TRAINING = "Education/Training"
    		GAMES_HOBBIES = "Games &amp; Hobbies"
    		GAMES_HOBBIES_AUTOMOTIVE = "Games &amp; Hobbies/Automotive"
    		GAMES_HOBBIES_AVIATION = "Games &amp; Hobbies/Aviation"
    		GAMES_HOBBIES_HOBBIES = "Games &amp; Hobbies/Hobbies"
    		GAMES_HOBBIES_OTHER_GAMES = "Games &amp; Hobbies/Other Games"
    		GAMES_HOBBIES_VIDEO_GAMES = "Games &amp; Hobbies/Video Games"
    		GOVERNMENT_ORGANIZATIONS = "Government &amp; Organizations"
    		GOVERNMENT_ORGANIZATIONS_LOCAL = "Government &amp; Organizations/Local"
    		GOVERNMENT_ORGANIZATIONS_NATIONAL = "Government &amp; Organizations/National"
    		GOVERNMENT_ORGANIZATIONS_NON_PROFIT = "Government &amp; Organizations/Non-Profit"
    		GOVERNMENT_ORGANIZATIONS_REGIONAL = "Government &amp; Organizations/Regional"
    		HEALTH = "Health"
    		HEALTH_ALTERNATIVE_HEALTH = "Health/Alternative Health"
    		HEALTH_FITNESS_NUTRITION = "Health/Fitness &amp; Nutrition"
    		HEALTH_SELF_HELP = "Health/Self-Help"
    		HEALTH_SEXUALITY = "Health/Sexuality"
    		KIDS_FAMILY = "Kids &amp; Family"
    		MUSIC = "Music"
    		NEWS_POLITICS = "News &amp; Politics"
    		RELIGION_SPIRITUALITY = "Religion &amp; Spirituality"
    		RELIGION_SPIRITUALITY_BUDDHISM = "Religion &amp; Spirituality/Buddhism"
    		RELIGION_SPIRITUALITY_CHRISTIANITY = "Religion &amp; Spirituality/Christianity"
    		RELIGION_SPIRITUALITY_HINDUISM = "Religion &amp; Spirituality/Hinduism"
    		RELIGION_SPIRITUALITY_ISLAM = "Religion &amp; Spirituality/Islam"
    		RELIGION_SPIRITUALITY_JUDAISM = "Religion &amp; Spirituality/Judaism"
    		RELIGION_SPIRITUALITY_OTHER = "Religion &amp; Spirituality/Other"
    		RELIGION_SPIRITUALITY_SPIRITUALITY = "Religion &amp; Spirituality/Spirituality"
    		SCIENCE_MEDICINE = "Science &amp; Medicine"
    		SCIENCE_MEDICINE_MEDICINE = "Science &amp; Medicine/Medicine"
    		SCIENCE_MEDICINE_NATURAL_SCIENCES = "Science &amp; Medicine/Natural Sciences"
    		SCIENCE_MEDICINE_SOCIAL_SCIENCES = "Science &amp; Medicine/Social Sciences"
    		SOCIETY_CULTURE = "Society &amp; Culture"
    		SOCIETY_CULTURE_HISTORY = "Society &amp; Culture/History"
    		SOCIETY_CULTURE_PERSONAL_JOURNALS = "Society &amp; Culture/Personal Journals"
    		SOCIETY_CULTURE_PHILOSOPHY = "Society &amp; Culture/Philosophy"
    		SOCIETY_CULTURE_PLACES_TRAVEL = "Society &amp; Culture/Places &amp; Travel"
    		SPORTS_RECREATION = "Sports &amp; Recreation"
    		SPORTS_RECREATION_AMATEUR = "Sports &amp; Recreation/Amateur"
    		SPORTS_RECREATION_COLLEGE_HIGH_SCHOOL = "Sports &amp; Recreation/College &amp; High School"
    		SPORTS_RECREATION_OUTDOOR = "Sports &amp; Recreation/Outdoor"
    		SPORTS_RECREATION_PROFESSIONAL = "Sports &amp; Recreation/Professional"
    		TECHNOLOGY = "Technology"
    		TECHNOLOGY_GADGETS = "Technology/Gadgets"
    		TECHNOLOGY_TECH_NEWS = "Technology/Tech News"
    		TECHNOLOGY_PODCASTING = "Technology/Podcasting"
    		TECHNOLOGY_SOFTWARE_HOW_TO = "Technology/Software How-To"
    		TV_FILM = "TV &amp; Film"
    	end
    end
  end
end